name: '${COMPOSE_PROJECT_NAME}'
services:
  mysql:
    image: mysql:8.1
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./.srv/database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: '${WORDPRESS_DB_PASSWORD}'
      MYSQL_DATABASE: '${WORDPRESS_DB_NAME}'
      MYSQL_USER: '${WORDPRESS_DB_USER}'
      MYSQL_PASSWORD: '${WORDPRESS_DB_PASSWORD}'

  wordpress:
    image: wordpress:6.6.1-php8.1-apache
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: '${WORDPRESS_DB_HOST}'
      WORDPRESS_DB_USER: '${WORDPRESS_DB_USER}'
      WORDPRESS_DB_PASSWORD: '${WORDPRESS_DB_PASSWORD}'
      WORDPRESS_DB_NAME: '${WORDPRESS_DB_NAME}'
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG', true);
        define('WP_DEBUG_DISPLAY', true );
        define('WP_DEBUG_LOG', true );
        define('SCRIPT_DEBUG', true );

    volumes:
      - './app/theme/:/var/www/html/wp-content/themes/dk'
      - './app/plugins/myblock:/var/www/html/wp-content/plugins/dk'
      - './.srv/wordpress/:/var/www/html'
      - './.srv/log/:/var/log'
      - './custom.ini:/usr/local/etc/php/conf.d/custom.ini'
      - './wp-config.php:/var/www/html/wp-config.php'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    links:
      - mysql:mysql
    ports:
      - "8181:80"
    restart: always
    environment:
      MYSQL_USERNAME: '${WORDPRESS_DB_USER}'
      MYSQL_ROOT_PASSWORD: '${WORDPRESS_DB_PASSWORD}'
      PMA_HOST: '${WORDPRESS_DB_HOST}'
    volumes:
      - './custom.ini:/usr/local/etc/php/conf.d/custom.ini'

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui
